/* ═══════════════════════════════════════════════════════════════════════
   IMPACT ORBITS — concentric rings of orbiting dots + a live connection web,
   drawn on the full-bleed #impactOrbits canvas behind the "30+ schools"
   carousel/stats.

   The rings are modelled in 3D: each is a flat CIRCLE on a plane TILTED back
   around the X axis, then PERSPECTIVE-projected. So a ring reads as a disc
   receding into the screen — dots at the back sit higher and smaller, dots at
   the front lower and larger. Modelling true circles means equal-angle
   sampling already gives even spacing (no ellipse bunching to correct). Rings
   counter-rotate; inner rings fade toward the background (aerial depth).

   The control panel (js/impact-carousel.js) drives everything through the live
   config at window.__impactOrbits.cfg — read every frame — and calls
   .rebuild() when dots-per-ring changes.
   ═══════════════════════════════════════════════════════════════════════ */
(function () {
  'use strict';

  const canvas = document.getElementById('impactOrbits');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');

  /* ── Per-ring base arrays (index 0 = OUTER ring) ───────────────────────────
     Generated by geom() from cfg.ringCount + cfg.ringGap so the count and the
     spacing are both live-tunable. Ring 0 is the outer ring; each ring inward
     is cfg.ringGap px smaller, a touch faster, fainter, and its dots smaller. */
  const OUTER_RADIUS = 520;            // outer ring world radius (px) at ringScale 1
  let RADII = [], SPEED = [], DIRECTION = [], FAINTNESS = [], DOT_SCALE = [], YOFF = [];
  let RINGS = 0;
  function geom() {
    RINGS = Math.max(1, cfg.ringCount | 0);
    RADII = []; SPEED = []; DIRECTION = []; FAINTNESS = []; DOT_SCALE = []; YOFF = [];
    for (let o = 0; o < RINGS; o++) {
      RADII[o]     = Math.max(30, OUTER_RADIUS - o * cfg.ringGap);
      SPEED[o]     = 0.14 + o * 0.07;      // rad/s, quicker toward the centre
      DIRECTION[o] = (o % 2 === 0) ? 1 : -1;// counter-rotate alternate rings
      FAINTNESS[o] = Math.min(0.6, o * 0.23);
      DOT_SCALE[o] = Math.max(0.3, 1 - o * 0.12);
      YOFF[o]      = 0;
    }
    if (!phase || phase.length !== RINGS) phase = new Float64Array(RINGS);
  }

  const DOT_BASE   = 6.0;   // base dot radius (px), before cfg.dotSize & depth
  const BOB_AMP    = 5;     // vertical bob amplitude (px, world)
  const BOB_SPEED  = 0.9;   // vertical bob rate (rad/s)
  const CHAOS_AMP  = 42;    // px of positional wander (world) at cfg.chaos = 1
  const BG         = [202, 240, 254];   // faint dots blend toward this (matches the glow)
  const PALETTE    = [
    [252, 195, 11], [38, 189, 226], [86, 192, 43], [249, 155, 28], [232, 102, 176],
  ];

  const MAX_DIST = 150, FADE_DIST = 78, MAX_LINKS = 3, DENSITY = 0.72,
        LINK_OPACITY = 0.5, LINK_COLOR = [150, 140, 70];

  const EDGE_FADE = 90;   // px band at each canvas edge where dots fade to 0
                          // (kills the hard half-circle clip at the boundary)

  /* ── LIVE config — the control panel mutates this ──────────────────────── */
  const cfg = {
    dotSize:   1.98,  // × DOT_BASE
    speed:     1.0,   // × SPEED[]
    chaos:     0.26,  // 0..1 positional randomness
    links:     true,  // draw connection lines?
    ringScale: 1.34,  // × RADII
    count:     28,    // dots PER RING
    ringCount: 4,     // number of rings
    ringGap:   138,   // px between consecutive rings (at ringScale 1)
    rotX:      9,     // whole-system rotation about X (deg): 0 = face-on, 90 = edge-on
    rotY:      0,     // whole-system rotation about Y (deg)
    rotZ:      0,     // whole-system rotation about Z / roll (deg)
    offX:      76,    // move the whole orbit — screen X (px)
    offY:      278,   // move the whole orbit — screen Y (px)
    offZ:      -166,  // move the whole orbit — depth (px); + = farther/smaller
    persp:     1190,  // perspective focal length (px); lower = deeper 3D
  };

  const TWO_PI = Math.PI * 2, DEG = Math.PI / 180;

  /* ── (Re)build the dot set — call on ring-count / gap / dots-per-ring change */
  let dots = [];
  let phase;
  function rebuild() {
    geom();                 // regenerate ring geometry from cfg first
    dots = [];
    let id = 0;
    for (let o = 0; o < RINGS; o++) {
      const n = Math.max(1, cfg.count | 0);
      for (let i = 0; i < n; i++) {
        const base = PALETTE[id % PALETTE.length], t = FAINTNESS[o];
        const col = 'rgb(' +
          Math.round(base[0] + (BG[0] - base[0]) * t) + ',' +
          Math.round(base[1] + (BG[1] - base[1]) * t) + ',' +
          Math.round(base[2] + (BG[2] - base[2]) * t) + ')';
        dots.push({
          ring: o, id,
          frac0: i / n,
          color: col,
          rScale: DOT_SCALE[o],
          bobPhase: id * 2.399963,
          cphX: (Math.sin(id * 12.9898) * 43758.5453 % 1) * TWO_PI,
          cphY: (Math.sin(id * 78.233) * 12345.6789 % 1) * TWO_PI,
          x: 0, y: 0, depth: 0,
        });
        id++;
      }
    }
  }
  rebuild();

  function hash01(a, b) {
    const lo = a < b ? a : b, hi = a < b ? b : a;
    let h = (Math.imul(lo, 73856093) ^ Math.imul(hi, 19349663)) >>> 0;
    h ^= h >>> 13; h = Math.imul(h, 1274126177) >>> 0;
    return (h >>> 0) / 4294967296;
  }

  /* ── Sizing (DPR-aware; clientW/H so the reveal scale/blur doesn't skew it) */
  let cx = 0, cy = 0;
  function resize() {
    const w = canvas.clientWidth || 1, h = canvas.clientHeight || 1;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.round(w * dpr);
    canvas.height = Math.round(h * dpr);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    cx = w / 2; cy = h / 2;
  }

  // 1 in the interior, ramping to 0 within EDGE_FADE px of the nearest edge.
  function edgeAlpha(x, y) {
    const d = Math.min(x, y, cx * 2 - x, cy * 2 - y);
    return d >= EDGE_FADE ? 1 : Math.max(0, d / EDGE_FADE);
  }

  const order = [];
  const cand = [];
  function frame(dt, elapsed) {
    const rs = cfg.ringScale, ch = cfg.chaos, dpx = DOT_BASE * cfg.dotSize;
    // whole-system rotation about all three axes (applied X → Y → Z)
    const ax = cfg.rotX * DEG, ay = cfg.rotY * DEG, az = cfg.rotZ * DEG;
    const sinX = Math.sin(ax), cosX = Math.cos(ax);
    const sinY = Math.sin(ay), cosY = Math.cos(ay);
    const sinZ = Math.sin(az), cosZ = Math.cos(az);
    const F = cfg.persp, oX = cfg.offX, oY = cfg.offY, oZ = cfg.offZ;
    for (let o = 0; o < RINGS; o++) phase[o] += SPEED[o] * cfg.speed * dt;

    for (let d = 0; d < dots.length; d++) {
      const dot = dots[d], o = dot.ring, r = RADII[o] * rs;
      let u = dot.frac0 + DIRECTION[o] * phase[o] / TWO_PI;
      u = ((u % 1) + 1) % 1;
      const ang = u * TWO_PI;
      // world point on the flat circle (x horizontal, z in-plane, y = bob height)
      let wx = r * Math.cos(ang);
      let wz = r * Math.sin(ang);
      let wy = YOFF[o];
      if (ch > 0) {                                   // organic wander (world)
        wx += ch * CHAOS_AMP * Math.sin(elapsed * 0.7 + dot.cphX);
        wz += ch * CHAOS_AMP * Math.cos(elapsed * 0.9 + dot.cphY);
      }
      wy += Math.abs(Math.sin(elapsed * BOB_SPEED + dot.bobPhase)) * BOB_AMP;
      // rotate X, then Y, then Z
      const y1 = wy * cosX - wz * sinX, z1 = wy * sinX + wz * cosX, x1 = wx;
      const x2 = x1 * cosY + z1 * sinY, z2 = -x1 * sinY + z1 * cosY, y2 = y1;
      const x3 = x2 * cosZ - y2 * sinZ, y3 = x2 * sinZ + y2 * cosZ, z3 = z2;
      // move the whole orbit (offZ shifts depth), then perspective-project
      const depth = z3 + oZ;                           // + = farther back
      const persp = F / Math.max(60, F + depth);       // clamp denom > 0
      dot.x = cx + oX + x3 * persp;
      dot.y = cy + oY + y3 * persp;
      dot.depth = depth;
      dot.px = persp;
    }

    ctx.clearRect(0, 0, cx * 2, cy * 2);

    if (cfg.links) {
      const maxSq = MAX_DIST * MAX_DIST, seen = new Set(), denom = MAX_DIST - FADE_DIST;
      for (let a = 0; a < dots.length; a++) {
        const da = dots[a];
        cand.length = 0;
        for (let b = 0; b < dots.length; b++) {
          if (b === a) continue;
          const db = dots[b], dx = db.x - da.x, dy = db.y - da.y, d2 = dx * dx + dy * dy;
          if (d2 <= maxSq) cand.push({ b, d2 });
        }
        cand.sort((p, q) => p.d2 - q.d2);
        const keep = Math.min(MAX_LINKS, cand.length);
        for (let k = 0; k < keep; k++) {
          const b = cand[k].b, db = dots[b];
          const key = da.id < db.id ? da.id * 100000 + db.id : db.id * 100000 + da.id;
          if (seen.has(key)) continue;
          seen.add(key);
          if (hash01(da.id, db.id) >= DENSITY) continue;
          const dist = Math.sqrt(cand[k].d2);
          let fade = dist <= FADE_DIST ? 1 : Math.max(0, 1 - (dist - FADE_DIST) / denom);
          fade *= Math.min(edgeAlpha(da.x, da.y), edgeAlpha(db.x, db.y));
          if (fade <= 0) continue;
          ctx.strokeStyle = 'rgba(' + LINK_COLOR[0] + ',' + LINK_COLOR[1] + ',' +
            LINK_COLOR[2] + ',' + (LINK_OPACITY * fade).toFixed(3) + ')';
          ctx.lineWidth = 1;
          ctx.beginPath(); ctx.moveTo(da.x, da.y); ctx.lineTo(db.x, db.y); ctx.stroke();
        }
      }
    }

    // painter's order: farthest first so near dots sit on top
    order.length = dots.length;
    for (let i = 0; i < dots.length; i++) order[i] = i;
    order.sort((i, j) => dots[j].depth - dots[i].depth);
    for (let k = 0; k < order.length; k++) {
      const dot = dots[order[k]];
      const a = edgeAlpha(dot.x, dot.y);
      if (a <= 0) continue;
      ctx.globalAlpha = a;
      ctx.fillStyle = dot.color;
      ctx.beginPath();
      ctx.arc(dot.x, dot.y, Math.max(0.4, dpx * dot.rScale * dot.px), 0, TWO_PI);
      ctx.fill();
    }
    ctx.globalAlpha = 1;
  }

  /* ── Loop, gated to on-screen + tab-visible ────────────────────────────── */
  const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  let last = 0, elapsed = 0, running = false, onScreen = true;
  function tick(now) {
    if (!running) return;
    const dt = last ? Math.min(0.05, (now - last) / 1000) : 0;
    last = now; elapsed += dt;
    frame(dt, elapsed);
    if (running) requestAnimationFrame(tick);
  }
  function start() { if (running || reduce || !onScreen || document.hidden) return; running = true; last = 0; requestAnimationFrame(tick); }
  function stop() { running = false; }

  resize();
  window.addEventListener('resize', () => { resize(); if (reduce) frame(0, elapsed); });
  window.__impactOrbits = { cfg, rebuild, redraw: () => frame(0, elapsed) };

  if (reduce) {
    frame(0, 0);
  } else {
    // gate on the SCENE's scroll block, not the canvas: the canvas lives in a
    // fixed full-viewport stage and would always read as "on-screen".
    const gate = document.getElementById('impact') || canvas;
    if ('IntersectionObserver' in window) {
      new IntersectionObserver((e) => { onScreen = e[0].isIntersecting; if (onScreen) { resize(); start(); } else stop(); },
        { rootMargin: '300px' }).observe(gate);
    } else { start(); }
    document.addEventListener('visibilitychange', () => { document.hidden ? stop() : start(); });
  }
})();
